enix/kube-image-keeper

cmd/cache/main.go
see https://github.com/kubernetes-sigs/controller-runtime/issues/2173
=> fix: encode time in logs with ISO8601TimeEncoder

cmd/cache/main.go, helm/kube-image-keeper/templates/_helpers.tpl, helm/kube-image-keeper/templates/clusterrole.yaml, helm/kube-image-keeper/templates/clusterrolebinding.yaml, helm/kube-image-keeper/templates/controller-deployment.yaml, helm/kube-image-keeper/templates/garbage-collection-cron-job.yaml, helm/kube-image-keeper/templates/garbage-collection-role-binding.yaml, helm/kube-image-keeper/templates/garbage-collection-role.yaml, helm/kube-image-keeper/templates/garbage-collection-service-account.yaml, helm/kube-image-keeper/templates/mutatingwebhookconfiguration.yaml, helm/kube-image-keeper/templates/registry-statefulset.yaml, helm/kube-image-keeper/templates/registry-ui-deployment.yaml, helm/kube-image-keeper/templates/service.yaml, helm/kube-image-keeper/templates/webhook-certificate.yaml, helm/kube-image-keeper/templates/webhook-service.yaml, internal/registry/registry.go, test-helm-fullname-helper.sh
This PR tries to harmonize naming between helm resources and fix some naming issues as well.
1. Registry statefulset was originally named "cache-registry" at the time the project was also called "cache-registry". Thus, when reworking the chart, its name was replaced by a template to name it by the name of the project. Then, when the project was renamed kube-image-keeper, the registry name was templated as kube-image-keeper instead of cache-registry. This commit intend to fix this mistake and set a proper name for the registry.
2. All resources are now prefixed with the `kube-image-keeper.fullname` helper, which by default when following the installation steps in the readme is `kuik`. It still can be customized using values `nameOverride` and `fullnameOverride` or by giving another name …
=> Rename helm resources

helm/kube-image-keeper/templates/proxy-daemonset.yaml, helm/kube-image-keeper/values.yaml
When using cilium, removing hostIp from the daemonset helps to make it work, so we make this parameter configurable (while keeping the default of 127.0.0.1).
=> helm chart: make the proxy hostIp parameter configurable

internal/registry/registry_test.go
The layer and digests paths can be called randomly in any order, it then cause the test to fail when the order is not the one expected.
=> tests: fix Test_CacheImage fails randomly

helm/kube-image-keeper/templates/s3-registry-keys.yaml
We don't need to create a secret when setting `registry.persistence.s3ExistingSecret`. Creating it makes helm install fail.
=> Setting registry.persistence.s3ExistingSecret makes helm install fail

cmd/cache/main.go, controllers/cachedimage_controller.go, controllers/suite_test.go, helm/kube-image-keeper/templates/controller-deployment.yaml, helm/kube-image-keeper/values.yaml
It allows to put in cache or remove from the cache multiple images at the same time in order to speed up the process.
=> Allow to set the maximum concurrency in CachedImages operations

helm/kube-image-keeper/templates/garbage-collection-cron-job.yaml, helm/kube-image-keeper/templates/garbage-collection-role-binding.yaml, helm/kube-image-keeper/templates/garbage-collection-role.yaml, helm/kube-image-keeper/templates/garbage-collection-service-account.yaml, helm/kube-image-keeper/templates/registry-statefulset.yaml, helm/kube-image-keeper/values.yaml
Make `--delete-untagged` flag used with `registry garbage-collect` command configurable from helm chart.
**Rationale**:
Faced the bug in `registry` which makes it crash during garbage collection:
```
public.ecr.aws/docker/library/python
public.ecr.aws/docker/library/python: marking manifest sha256:281811c93dbf7b29719709c129230edfa1b10585d720f95c60363a358e49b62c 
public.ecr.aws/docker/library/python: marking blob sha256:d56c84cce2aab1191d519b6881efe21d463c69fdc5ec0c349dce4e5fde19d712
public.ecr.aws/docker/library/python: marking blob sha256:31e352740f534f9ad170f75378a84fe453d6156e40700b882d737a8f4a6988a3
public.ecr.aws/docker/library/python: marking blob sha256:cfcc276e4459ecb909a4257fdf7647034eb3b2ab1f0d0c0bba54856c39079c50
public.ecr.aws/docker/library/python: marking blob …
```
=> feat(helm): make delete-untagged registry flag configurable from helm

api/v1/pod_webhook.go, cmd/cache/main.go, helm/kube-image-keeper/templates/_helpers.tpl, helm/kube-image-keeper/templates/controller-deployment.yaml
The release namespace is already ignored by MutatingWebhookConfiguration.
=> refactor: remove ignore-namespace flag

api/v1/pod_webhook.go, api/v1/pod_webhook_test.go, controllers/pod_controller.go, controllers/pod_controller_test.go, internal/registry/registry.go, internal/registry/registry_test.go
=> fix: hash container names that are too long to be used as annotation key

LICENSE, Makefile, README.md, docs/high-availability.md, docs/metrics.md, helm/kube-image-keeper/README.md.gotmpl, helm/kube-image-keeper/values.yaml
- many small fixes (e.g. the documentation for podMonitors incorrectly referenced serviceMonitors instead; minor typos in some commands...)
- rewording and (subjective :)) improvement of HA and metrics docs
- add some limitations/caveats in README
- add Makefile target to keep Helm README template in sync with the repository README file, and update Helm README template
- update LICENSE with current year
=> docs: many small fixes and improvements

cmd/proxy/main.go, helm/kube-image-keeper/templates/proxy-daemonset.yaml, helm/kube-image-keeper/values.yaml
Currently we have more than 1k of CRDs installed in the cluster (because of Crossplane) so proxy start takes ~34 seconds.
Nodes are dynamically created and destroyed hundreds times per day as they are used as build nodes for CI/CD. So build pods often land on fresh nodes with images pointing to Kuik proxy that has not fully booted yet and get "dial tcp [::1]:7439: connect: connection refused" error and fail (see https://github.com/enix/kube-image-keeper/issues/102 for more details).
Increasing Kube API rate limits to 100 qps and 500 burst makes proxy start almost instantly and solves this problem. This PR makes these settings configurable from helm chart.
Tested on EKS cluster.
=> feat(proxy): make Kube client throttling rates configurable

cmd/cache/main.go, controllers/cachedimage_controller.go, controllers/pod_controller.go, controllers/suite_test.go
Finalizer on Pods were used to handle the expiry of CachedImages before deleting Pods because the logic of setting the `expiresAt` field was handled by the PodController. The goal of this PR is to compute all CachedImages' related information on the CachedImagesController side. The finalizer on Pods is thus no longer needed.
This PR also includes a fix: when an image get used by more pods (eg. scaling of a deployment), the pod count status was not updated.
⚠️ Pods from previous deployments will still have the kuik finalizer on Pods. Since after this change the controller does not remove finalizers, we should find a way to remove all kuik finalizers on pods when upgrading.
Closes #135
=> fix(controllers): remove pods finalizer

internal/registry/registry.go
By default remote.Image/remote.Write will copy only one platform of the multi-platform image. If such image is used and cached by Kuik, aarch64/linux fails to start immediately with error 1. Presumably this happens because go-containerimage library is using amd64/linux as [default platform](https://github.com/google/go-containerregistry/blob/v0.12.1/pkg/v1/remote/options.go#L51) and only one image gets cached in internal registry instead of full set of platforms.
It's possible to workaround this by finding image alternatives which contain architecture in their name or tag (e.g. use `arm64v8/docker:20-dind` instead of `library/docker:20-dind`, but it would be more convenient if Kuik could support such images out of the box.
Fixes https://github.com/enix/kube-image-keeper/issues/104.
=> feat(controller): multi-platform images support

controllers/cachedimage_controller.go
Restarting a controller reset the expiresAt field, preventing images from expiring at the right time.
=> fix(controller): don't reset expiresAt field on startup

cmd/proxy/main.go, helm/kube-image-keeper/templates/proxy-daemonset.yaml, helm/kube-image-keeper/values.yaml, internal/proxy/server.go
This PR adds the `--bind-address` option to the proxy (defaulting to ":8082").
It is backward compatible and can be used to deploy kube-image-keeper in hostNetwork mode as described in #229 .
=> feat(proxy): allow to configure the proxy bind address

helm/kube-image-keeper/templates/proxy-daemonset.yaml, helm/kube-image-keeper/values.yaml
Before we had to configure the port and host in the values, now it works by default.
=> fix(proxy): make readiness probe work out of the box in hostNetwork mode

docs/high-availability.md, helm/kube-image-keeper/templates/registry-pvc.yaml, helm/kube-image-keeper/templates/registry-statefulset.yaml, helm/kube-image-keeper/values.yaml
I've added the ability to override the AccessMode for the PVC on the Registry for situations where you are using a PVC which may support ReadWriteMany (for example for EFS CSI Driver), as described in #245
Closes enix/kube-image-keeper#245
=> feat(registry-statefulset): added optional access mode override

helm/kube-image-keeper/templates/garbage-collection-cron-job.yaml, helm/kube-image-keeper/values.yaml
Chart : configure docker image for the registry garbage collection cronjob in `values.yaml` .
The default values of `{repository: bitnami/kubectl, tag: "latest"}`  match the existing hardcoded values;
providing a custom docker image for the cronjob should fix #275.
=> feat(chart): configure the garbage collection cronjob image

api/core/v1/pod_webhook.go, api/core/v1/pod_webhook_test.go, cmd/cache/main.go
Removed in controller-runtime v0.15.0 https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.15.0
=> fix(controller): manually add a decoder since its not injected anymore

internal/proxy/bearer.go
The `response.Body` from the first `http.Get()` call in `NewBearer()` is not closed. This leaks connections to the `registry` server and can result in substantial memory usage, as the registry allocates a 4MB buffer for each connection and neither end enforces an idle timeout.
Fixes #378
=> fix: http connection leak in NewBearer()

api/core/v1/pod_webhook.go
fix: Ignore pod patching failures during startup
Note: this is a copy of #392, which auto-closed when I renamed my branch in an attempt to follow conventionalcommits.org
Summary
---------
Patch failures in `pod_webhook.Start()` abort the `controller` process and may result in crash looping.
We've experienced this on a test cluster, where we have 8 pods out of ~1100 that fail return an error on the "no op" patch attempt in `Start()`.
As I believe the code within `Start()` is an optimization to eagerly create `CachedImages`, but otherwise not required to function properly, this patch will instead log the `err` and continue on to the next pod.
Patch Failure Details
--------------------
Here's a sample of the patch failure:
```
The Pod "xxx-yyy-zzz" is invalid: spec: Forbidden: pod updates …
```
=> fix: Ignore pod patching failures during startup

helm/kube-image-keeper/templates/garbage-collection-cron-job.yaml, helm/kube-image-keeper/values.yaml
=> feat(helm): enhance garbage collector cronjob

docs/high-availability.md, helm/kube-image-keeper/templates/_helpers.tpl, helm/kube-image-keeper/templates/registry-deployment.yaml, helm/kube-image-keeper/values.yaml
• added GCS support with service account key
• upgraded version of registry (2.8.2 doesn't have GCS plugin =/)
• added basic docs for GCS support
=> feat: add GCS support

api/core/v1/pod_webhook.go, api/core/v1/pod_webhook_test.go, cmd/cache/main.go, helm/kube-image-keeper/templates/controller-deployment.yaml, helm/kube-image-keeper/values.yaml
This PR adds a new parameter called --accept-images, which behaves much like the --ignore-images parameter, except it provides a way to specify a whitelist of image regexes to rewrite. This check is done after ignore-images, so one can still specify a blacklist.
Use case: 
- We want to cache public images from certain repos to optimize traffic and performance, without exposing private images. We understand that KEP 2535 will solve this issue in term, but it will only enter alpha stage in v1.32
- The current --ignore-images parameter doesn't do it for us, because Golang's regexp engine doesn't support negative lookaheads (meaning we can't make a whitelist out of this blacklist)
- We have added the --accept-images parameter, which, when it's not empty, will only rewrite images that match …
=> feat: Add accept-images parameter to whitelist images

README.md
What do you think @zifeo? Is it clearer?
closes #440
=> docs: image filtering

api/kuik/v1alpha1/repository_types.go, config/crd/bases/kuik.enix.io_repositories.yaml, helm/kube-image-keeper/crds/repository-crd.yaml, internal/controller/kuik/repository_controller.go
- fixes #451
- "1d" was among `updateInterval` examples, but `ParseDuration` doesn't support it, remove from doc (*)
- catch and report negative `updateInterval`
(*) This is not supported, because the actual size of a day is not trivial (DST, leap sec...)
=> fix: Duration doesn't actually support 'd' suffix, warn on negative Duration

helm/kube-image-keeper/templates/garbage-collection-cron-job.yaml, helm/kube-image-keeper/values.yaml
This PR adds the ability to add securityContext to the pod and container in the garbage collection CronJob.
Many environments have policies that encourage or enforce specific securityContext to be defined. The garbage collection CronJob seems to be the only pod in the Helm Chart that currently does not support this.
=> feat(helm): securityContext for garbage collection pod and container

helm/kube-image-keeper/templates/_helpers.tpl, helm/kube-image-keeper/templates/clusterrole.yaml, helm/kube-image-keeper/templates/clusterrolebinding.yaml, helm/kube-image-keeper/templates/registry-deployment.yaml, helm/kube-image-keeper/templates/registry-serviceaccount.yaml, helm/kube-image-keeper/templates/registry-statefulset.yaml, helm/kube-image-keeper/templates/serviceaccount.yaml, helm/kube-image-keeper/values.yaml, test/helm_test.go
Allow users to control RBAC and ServiceAccount creation through Helm, per https://v3-1-0.helm.sh/docs/chart_best_practices/rbac/
=> Support RBAC and ServiceAccount configuration (fixes #500)
